% This is an autogenerated sample test for file rockPaperScissors
classdef testrockPaperScissors < matlab.unittest.TestCase
    methods (Test)
        function test_rockPaperScissors(testCase)
            % Specify the input(s) of rockPaperScissors
            player1Choice = "rock";
            player2Choice = "scissors";

            % Exercise the function rockPaperScissors
            actualOutput_result = rockPaperScissors(player1Choice,player2Choice);

            % Specify the expected output(s) of rockPaperScissors
            expectedOutput_result = "Player 1 wins";

            testCase.verifyEqual(actualOutput_result, expectedOutput_result);
        end
    end
end